name: Fadzli Shah
favicon: null
layout_spectrum: 0.25652
typography_spectrum: 0.38218
title: Where Fadzli thinks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e8e8'
    - '#acb2b6'
    - '#222222'
    - '#ffe026'
    - '#b5a924'
  brandStrength: 0.75
  lightness: 0.19389018532820046
  saturation: 0.75
  rhythmicContrast: 0.47340575815178454
purpose: []
